require("mods.base.prototype.Tile.grass")
require("mods.base.prototype.TileGroup.ground")
require("mods.base.prototype.TileGroup.mountain")
require("mods.base.prototype.TileGroup.void")
require("mods.base.prototype.TileGroup.water")
